# Use the official GoCD Alpine agent as the base image
FROM gocd/gocd-agent-alpine:v25.1.0

USER root

# PowerShell 7.5

WORKDIR /tmp
RUN apk add --no-cache --quiet ca-certificates less ncurses-terminfo-base krb5-libs libgcc libintl libssl3 libstdc++ tzdata userspace-rcu zlib icu-libs curl
RUN apk -X https://dl-cdn.alpinelinux.org/alpine/edge/main add --no-cache --quiet lttng-ust openssh-client
RUN curl -L https://github.com/PowerShell/PowerShell/releases/download/v7.5.0/powershell-7.5.0-linux-musl-x64.tar.gz -o /tmp/powershell.tar.gz
RUN mkdir -p /opt/microsoft/powershell/7
RUN tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7
RUN chmod +x /opt/microsoft/powershell/7/pwsh
RUN ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh
RUN rm /tmp/powershell.tar.gz

# AWS

WORKDIR /tmp
RUN apk add --no-cache --quiet aws-cli
COPY .aws /home/go/.aws
RUN chown -R go /home/go/.aws

USER go

